version: '{build}'
clone_folder: c:\projects\fasttext
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- echo %generator%

before_build:
- cmd: >-
    mkdir build
    
    cd build
    
    cmake --version

    cmake .. -G %generator%
    
build:
  project: c:\projects\fasttext\build\fasttext.sln
  parallel: true 

after_build:
  7z a %APPVEYOR_BUILD_FOLDER%\build\fasttext-win64-latest-%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%

artifacts:
  - path: build\fasttext-win64-latest-$(CONFIGURATION).zip
    name: fastText-win64-%CONFIGURATION%

deploy:
  release: fastText-latest-build$(appveyor_build_version)
  description: 'The latest binary build $(appveyor_build_version) of fastText for 64 bit Windows, using VS2017'
  provider: GitHub
  auth_token:
    secure: w6RhxxgTQp67I0w3mL1oSQXUZpmhnedD8uWFMyHaubLK0t0+cKWt5uLPCoHq2XbL
  artifact: build\fasttext-win64-latest-$(CONFIGURATION).zip
  draft: true
  prerelease: false
  force_update: false
  on:
    branch: master